/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GPSCoordinates {
    latitude: number;
    longitude: number;
}
export interface Asset {
    assetId: string;
    gpsCoordinates: GPSCoordinates;
    name: string;
    locationId: string;
    timestamp: bigint;
    category: string;
    remarks: string;
    photos: Array<string>;
    condition: string;
}
export enum DeleteResult {
    success = "success",
    assetNotFound = "assetNotFound"
}
export interface backendInterface {
    deleteAsset(assetId: string): Promise<DeleteResult>;
    exportAssetVerifications(): Promise<Array<Asset>>;
    findAssetsByName(name: string): Promise<Array<Asset>>;
    getAllAssets(): Promise<Array<Asset>>;
    getAssetCountsByCategory(): Promise<Array<[string, bigint]>>;
    getAssetsByLocation(locationId: string): Promise<Array<Asset>>;
    getLocationCountsByCondition(): Promise<Array<[string, Array<[string, bigint]>]>>;
    submitAssetCheck(assetId: string, name: string, category: string, locationId: string, condition: string, remarks: string, latitude: number, longitude: number, photos: Array<string>): Promise<void>;
    updateAssetStatus(assetId: string, condition: string, remarks: string, latitude: number, longitude: number, photos: Array<string>): Promise<void>;
}
import type { DeleteResult as _DeleteResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteAsset(arg0: string): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAsset(arg0);
                return from_candid_DeleteResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAsset(arg0);
            return from_candid_DeleteResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportAssetVerifications(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAssetVerifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAssetVerifications();
            return result;
        }
    }
    async findAssetsByName(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.findAssetsByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findAssetsByName(arg0);
            return result;
        }
    }
    async getAllAssets(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssets();
            return result;
        }
    }
    async getAssetCountsByCategory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetCountsByCategory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetCountsByCategory();
            return result;
        }
    }
    async getAssetsByLocation(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetsByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetsByLocation(arg0);
            return result;
        }
    }
    async getLocationCountsByCondition(): Promise<Array<[string, Array<[string, bigint]>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocationCountsByCondition();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocationCountsByCondition();
            return result;
        }
    }
    async submitAssetCheck(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: number, arg7: number, arg8: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssetCheck(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssetCheck(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateAssetStatus(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssetStatus(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssetStatus(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_DeleteResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: null;
} | {
    assetNotFound: null;
}): DeleteResult {
    return "success" in value ? DeleteResult.success : "assetNotFound" in value ? DeleteResult.assetNotFound : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
