/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'assetId' : string,
  'gpsCoordinates' : GPSCoordinates,
  'name' : string,
  'locationId' : string,
  'timestamp' : bigint,
  'category' : string,
  'remarks' : string,
  'photos' : Array<string>,
  'condition' : string,
}
export type DeleteResult = { 'success' : null } |
  { 'assetNotFound' : null };
export interface GPSCoordinates { 'latitude' : number, 'longitude' : number }
export interface _SERVICE {
  'deleteAsset' : ActorMethod<[string], DeleteResult>,
  'exportAssetVerifications' : ActorMethod<[], Array<Asset>>,
  'findAssetsByName' : ActorMethod<[string], Array<Asset>>,
  'getAllAssets' : ActorMethod<[], Array<Asset>>,
  'getAssetCountsByCategory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAssetsByLocation' : ActorMethod<[string], Array<Asset>>,
  'getLocationCountsByCondition' : ActorMethod<
    [],
    Array<[string, Array<[string, bigint]>]>
  >,
  'submitAssetCheck' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      Array<string>,
    ],
    undefined
  >,
  'updateAssetStatus' : ActorMethod<
    [string, string, string, number, number, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];