/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeleteResult = IDL.Variant({
  'success' : IDL.Null,
  'assetNotFound' : IDL.Null,
});
export const GPSCoordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Asset = IDL.Record({
  'assetId' : IDL.Text,
  'gpsCoordinates' : GPSCoordinates,
  'name' : IDL.Text,
  'locationId' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'remarks' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteAsset' : IDL.Func([IDL.Text], [DeleteResult], []),
  'exportAssetVerifications' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'findAssetsByName' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
  'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'getAssetCountsByCategory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAssetsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
  'getLocationCountsByCondition' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))))],
      ['query'],
    ),
  'submitAssetCheck' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateAssetStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeleteResult = IDL.Variant({
    'success' : IDL.Null,
    'assetNotFound' : IDL.Null,
  });
  const GPSCoordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Asset = IDL.Record({
    'assetId' : IDL.Text,
    'gpsCoordinates' : GPSCoordinates,
    'name' : IDL.Text,
    'locationId' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'remarks' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteAsset' : IDL.Func([IDL.Text], [DeleteResult], []),
    'exportAssetVerifications' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'findAssetsByName' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
    'getAllAssets' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'getAssetCountsByCategory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAssetsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
    'getLocationCountsByCondition' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))))],
        ['query'],
      ),
    'submitAssetCheck' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateAssetStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };